CREATE DATABASE P5;

USE P5;

CREATE TABLE CATEGORIES
(ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOM VARCHAR(80),
LINK_OFF VARCHAR(80),
PRIMARY KEY (ID)
)ENGINE=INNODB;

CREATE TABLE PRODUIT(
PRODUIT_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOM VARCHAR(200),
PRODUIT_URL VARCHAR(150),
STORE VARCHAR(300),
NUTRISCORE INT,
CATEGORIE_ID INT UNSIGNED,
PRIMARY KEY (PRODUIT_ID),
CONSTRAINT fk_ok
FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIES (ID)
)ENGINE=INNODB;


CREATE TABLE SUBSTITUT(
SUBSTITUT_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOM VARCHAR(80),
STORE VARCHAR(80),
SUBSTITUT_URL VARCHAR(100),
DESCRIPTION VARCHAR(200),
PRIMARY KEY (SUBSTITUT_ID)
)ENGINE=INNODB;
